spring:
  config:
    import:
      - application-db.yml
      - application-aws.yml
      - application-security.yml

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: ${CLIENT_NAME}
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - profile_image
              - account_email
              - birthday
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  profiles:
    include: security
