spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: ${CLIENT_NAME}
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT-SECRET}
            redirect-uri: ${REDIRECT-URI}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - profile_image
              - account_email
              - birthday
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  client-secret: ${JWT_CLIENT_SECRET}
  token-expire: ${JWT_TOKEN_EXPIRE}
  refresh-token-expire: ${JWT_REFRESH_TOKEN_EXPIRE}
  issuer: ${JWT_ISSUER}



