spring:
  config:
    import:
      - application-db.yml
      - application-aws.yml
      - application-security.yml

sentry:
  dsn: https://7d8643441c5c41a6bdbbcecebb5d51e7@o4504786657345536.ingest.sentry.io/4504786658918400
  traces-sample-rate: 1.0