version: '3'
services:
  mysql:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    env_file:
      - ../env/docker-compose.env
    container_name: hey-cake
    environment:
      TZ: Asia/Seoul
    volumes:
      - hey-cake:/var/lib/hey-cake/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  hey-cake: